;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/GeothermalSteam/Content/Localization/GeothermalSteam
DestinationPath=Mods/GameFeatures/GeothermalSteam/Content/Localization/GeothermalSteam
ManifestName=GeothermalSteam.manifest
ArchiveName=GeothermalSteam.archive
ResourceName=GeothermalSteam.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

